Client/urls.py
from django.conf.urls import patterns, url
from Client import views
import utilities

urlpatterns = patterns('',

 	url(r'^$', views.index, name='index'),
	url(r'^results$', views.results, name='results'),
	url(r'^watch$', views.watch, name='watch'),
	url(r'^delete$', views.delete, name='delete'),
	url(r'^check$', views.check, name='check'),
	# url(r'^summary_api/$', views.summary_api, name='summary_api'),
	# url(r'^api_result/$', views.api_result, name='api_result') 
)

# Start-up code
utilities.setClientIP()
utilities.getServerIPsfromMaster()
utilities.setServerIP()
utilities.connectToParentServer()

ReplicatedSystems/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'ReplicatedSystems.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('Client.urls', namespace='Client')),
    url(r'^admin/', include(admin.site.urls)),
]

Client/models.py
from django.db import models

# Create your models here.

Client/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, Http404
from django.core.urlresolvers import reverse
import utilities

# Create your views here.
def index(request):
	return render(request, 'Client/index.html', {})


def results(request):
	if 'search_query' not in request.GET or len(request.GET['search_query']) < 1 :
		return render(request, 'Client/index.html', { 'error_message': 'Let us know what you want to search for'})

	search_string = request.GET['search_query']

	page = '1'
	if 'page' in request.GET:
		page = request.GET['page']

	result = utilities.searchYoutube(search_string, page)
	return HttpResponse(result)

def watch(request):
	if 'v' not in request.GET or len(request.GET['v']) < 1:
		return render(request, 'Client/index.html', { 'error_message': 'Let us know what you want to search for'})

	video_id = request.GET['v']

	src = None
	if utilities.findVideo(video_id) :
		src = 'localhost'
	else :
		src = utilities.searchVideo(video_id)

	return HttpResponse(utilities.watchVideo(video_id,src))

def delete(request):
	if 'remove' in request.POST and len(request.POST['remove']) > 0 :
		video_id = request.POST['remove']
	
		msg = 'Unable to delete file as of now'
		if utilities.initiateDelete(video_id) :
			msg = 'Video has been deleted'

		return render(request, 'Client/index.html', { 'error_message': msg})

	video_list = utilities.getVideoList()
	return render(request, 'Client/delete.html', {'video_list': video_list})

def check(request):
	if 'v' not in request.GET or len(request.GET['v']) < 0:
		raise Http404('Video id not present')

	video_id = request.GET['v']
	if utilities.findVideo(video_id) :
		return HttpResponse('It\'s there')
	else :
		raise Http404('Video is not present')

Client/templates/Client/delete.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
	    <!-- Meta, title, CSS, favicons, etc. -->
	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!-- Bootstrap core CSS -->
		<link href="{% static 'Client/css/bootstrap.min.css' %}" rel="stylesheet">
		<!-- Custom CSS -->
		<link href="{% static 'Client/css/style.css' %}" rel="stylesheet">
		<title>
			R-Youtube
		</title>
	</head>

	<body>

		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
			    <div class="navbar-header">
			      <button id="toggle_button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'Client:index' %}" >R-YouTube</a>
			    </div>

			    <div class="collapse navbar-collapse" id="navbar-collapse">
			      <ul class="nav navbar-nav navbar-right">
			      <li id="about_item" class=""><a id="about" onclick="$('#aboutModal').modal()" href="#">About</a></li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>

		<!-- Modal -->
		<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="aboutModalLabel">R-YouTube</h4>
		      </div>
		      <div class="modal-body">
		        <b>Distributed Systems</b>
		       <p>
		        	<ul>
		        		<li><h6>Utkarsh Jaiswal</h6></li>
		        		<li><h6>Aniruddha Gupta</h6></li>
		        		<li><h6>Ankit Jain</h6></li>
		        		<li><h6>Shushman Chowdhary</h6></li>
		        	</ul>
		        </p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="container">
			{% if video_list %}
			<form class="form-horizontal" role="form" action="{% url 'Client:delete' %}" method="post">
			{% csrf_token %}
				<div class="form-group">
					{% for video in video_list %}
					<div class="col-sm-offset-2 col-sm-10">
					  <button type="submit" class="btn btn-default" name="remove" value="{{ video }}">Delete {{ video }}</button>
					</div>
					{% endfor %}
				</div>
			</form>
			{% endif %}
		</div><!-- /.container -->
		<hr>
		<div class="container">
			<footer>
				<b>Distributed Systems, Department of Computer Science and Engineering, IIT Kharagpur</b>
			</footer>
		</div>
		<!-- JQuery core javascript  -->
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<!-- Bootstrap core JavaScript -->
		<script src="{% static 'Client/js/bootstrap.min.js' %}"></script>
	</body>
</html>
	

Client/templates/Client/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
	    <!-- Meta, title, CSS, favicons, etc. -->
	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		
		<!-- Bootstrap core CSS -->
		<link href="{% static 'Client/css/bootstrap.min.css' %}" rel="stylesheet">
		<!-- Custom CSS -->
		<link href="{% static 'Client/css/style.css' %}" rel="stylesheet">
		<title>
			R-Youtube
		</title>
	</head>

	<body>

		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container-fluid">
			    <div class="navbar-header">
			      <button id="toggle_button" type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <a class="navbar-brand" href="{% url 'Client:index' %}" >R-YouTube</a>
			    </div>

			    <div class="collapse navbar-collapse" id="navbar-collapse">
			      <ul class="nav navbar-nav navbar-right">
			      <li id="about_item" class=""><a id="about" onclick="$('#aboutModal').modal()" href="#">About</a></li>
			      </ul>
			    </div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>

		<!-- Modal -->
		<div class="modal fade" id="aboutModal" tabindex="-1" role="dialog" aria-labelledby="aboutModalLabel" aria-hidden="true">
		  <div class="modal-dialog">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		        <h4 class="modal-title" id="aboutModalLabel">R-YouTube</h4>
		      </div>
		      <div class="modal-body">
		        <b>Distributed Systems</b>
		       <p>
		        	<ul>
		        		<li><h6>Utkarsh Jaiswal</h6></li>
		        		<li><h6>Aniruddha Gupta</h6></li>
		        		<li><h6>Ankit Jain</h6></li>
		        		<li><h6>Shushman Chowdhary</h6></li>
		        	</ul>
		        </p>
		      </div>
		      <div class="modal-footer">
		        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		      </div>
		    </div>
		  </div>
		</div>

		<div class="container">
			{% if error_message %}<div class="well"><strong>{{ error_message }}</strong></div>{% endif %}
			<form class="form-horizontal" role="form" action="{% url 'Client:results' %}" method="get">
				<div class="form-group">
					<label for="input_search_string" class="col-sm-2 control-label">R-YouTube Search:</label>
					<div class="col-sm-10">
						<input id="input_search_string" name="search_query" class="form-control" type="text"></input>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-offset-2 col-sm-10">
					  <button type="submit" class="btn btn-default">Search</button>
					</div>
				</div>
			</form>
		</div><!-- /.container -->
		<hr>
		<div class="container">
			<footer>
				<b>Distributed Systems, Department of Computer Science and Engineering, IIT Kharagpur</b>
			</footer>
		</div>
		<!-- JQuery core javascript  -->
		<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<!-- Bootstrap core JavaScript -->
		<script src="{% static 'Client/js/bootstrap.min.js' %}"></script>
	</body>
</html>
	